/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._admin._vocabulary;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.util.Date;
import java.text.*;
import javax.naming.*;
import net.sf.json.*;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.util.Map.Entry;
import com.cesa.common.*;
import com.cesa.dao.*;
import com.cesa.util.*;
import com.cesa.db.*;
import org.apache.log4j.Logger;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.math.NumberUtils;
import org.apache.commons.codec.digest.DigestUtils;

public class _vocabularyList__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      
	/*============================================================================
	 * @ Description : \u00ea\u00b4\u0080\u00eb\u00a6\u00ac\u00ec\u009e\u0090 \u00eb\u00a6\u00ac\u00ec\u008a\u00a4\u00ed\u008a\u00b8
	 *
	 * \u00ec\u009e\u0091\u00ec\u0084\u00b1\u00ec\u009d\u00bc : 2011.04.18
	 * \u00ec\u009e\u0091\u00ec\u0084\u00b1\u00ec\u009e\u0090 : \u00ec\u009d\u00b4\u00ec\u00a0\u0095\u00ec\u0088\u009c
	 ============================================================================*/

      out.write(_jsp_string0, 0, _jsp_string0.length);
      

	//Cache \uc5c6\uc74c
	response.setDateHeader("Expires", -1);
	response.setHeader("Pragma","no-cache");
	response.setHeader("Cache-Control","no-store"); //HTTP 1.0
	response.setHeader("Cache-Control","no-cashe"); //HTTP 1.1

	request.setCharacterEncoding("utf-8");

	String remoteAddr =request.getRemoteAddr();

	//\uc138\uc158 timeout \uc124\uc815
	//session.setMaxInactiveInterval(3600);

	//log
	Logger log = Logger.getLogger(this.getClass());

	String useBrowser = request.getHeader("User-Agent");
	if(useBrowser==null) useBrowser = "";

	// SiteContext getting
	SiteContext sc = SiteContext.getInstance();
	
	//admin
	boolean isAdminLogin = false;
	String adminID = "";
	String sPermission = "";
	String sGroup = "";
	
	//front
	boolean isFrontLogin = false;
	String sMemberId = "";
	String sMemberSeq = "";
	String sProjectSeq = "";
	

	if(	session.getAttribute("adminID") != null ){
		isAdminLogin = true;
		adminID = (String)session.getAttribute("adminID");
		sGroup = (String)session.getAttribute("sGroup");
	}
	else {
		isAdminLogin = false;
	}

	if(	session.getAttribute("sMemberId") != null ){
		isFrontLogin = true;
		sMemberId = (String)session.getAttribute("sMemberId");
		sMemberSeq = (String)session.getAttribute("sMemberSeq");
		sProjectSeq = (String)session.getAttribute("sProjectSeq");
	}
	else {
		isFrontLogin = false;
	}


	try{

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	/*============================================================================
	 * @ Description : \uad00\ub9ac\uc790\uc6a9 \ub808\uc774\uc544\uc6c3 \ud5e4\ub354
	 *
	 * \uc791\uc131\uc77c : 2010.12.16
	 * \uc791\uc131\uc790 : \uc6b0\uc9c4\ud638
	 ============================================================================*/

      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	/*============================================================================
	 * @ Description : \ub85c\uadf8\uc778\uc774 \ud544\uc694\ud55c \ud398\uc774\uc9c0\uc5d0 include \ud55c\ub2e4. (\uad00\ub9ac\uc790\uc6a9)
	 *
	 * \uc791\uc131\uc77c : 2010.12.16
	 * \uc791\uc131\uc790 : \uc6b0\uc9c4\ud638
	 ============================================================================*/

      out.write(_jsp_string0, 0, _jsp_string0.length);
      

	if( !isAdminLogin ){
		//ju.alertAndRedirect("Need Login", "/admin/login/login.jsp");
		out.println("<script language='javascript'>");
		out.println("alert(\"Need Login\");");
		out.println("self.location.replace('/admin/login/login.jsp');");
		out.println("</script>");
		return;
	}


      out.write(_jsp_string2, 0, _jsp_string2.length);
      
	int m1 = 0, m2 = 0, m3 = 0;

      out.write(_jsp_string3, 0, _jsp_string3.length);
      
	m1 = 2;
	m2 = 1;
	m3 = 1;

      out.write(_jsp_string4, 0, _jsp_string4.length);
      if(isAdminLogin){
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((adminID));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      }
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((m1==1 ? "on":"off"));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((m1==1 ? "on":"off"));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((m1==2 ? "on":"off"));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((m1==2 ? "on":"off"));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((m1==3 ? "on":"off"));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((m1==3 ? "on":"off"));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((m1==4 ? "on":"off"));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((m1==4 ? "on":"off"));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((m1==1 ? "" : "display:none;"));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((m1 == 1 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 1 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      
								//\uc288\ud37c \uad00\ub9ac\uc790\ub9cc \ubcf4\uc784
								if(sGroup.equals("0")){
							
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((m1 == 1 && m2 == 2 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 1 && m2 == 2 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      
								}
							
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((m1==2 ? "" : "display:none;"));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((m1 == 2 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 2 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((m1 == 2 && m2 == 2 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 2 && m2 == 2 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((m1==3 ? "" : "display:none;"));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((m1 == 3 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 3 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((m1==4 ? "" : "display:none;"));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((m1 == 4 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 4 && m2 == 1 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((m1 == 4 && m2 == 2 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((m1 == 4 && m2 == 2 ? "depth2_sel" : "depth2_nosel"));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
    // Params
	int currPage = Integer.parseInt(StringUtils.defaultString(request.getParameter("_currPage"),  "1"));
	String groupSeq = StringUtils.defaultString(request.getParameter("groupSeq"),  "");


	// Vars
	int totalCount = 0;
	RowSetMapper cRowSet = null;

	
	//\uadf8\ub8f9 select	1000\uc73c\ub85c \uc14b\ud305
	StringBuffer sbufSelect = new StringBuffer();
	cRowSet = GroupDAO.getInstance().groupList(1000, 1);
	sbufSelect.append("<select name='groupSeq'>");
	sbufSelect.append("<option value=''>\uc804\uccb4</option>");
	while(cRowSet.next()){
		if(groupSeq.equals(cRowSet.getString("seq"))){
			sbufSelect.append("<option value='"+cRowSet.getString("seq")+"' selected>"+cRowSet.getString("group_name")+"</option>");
		}
		else{
			sbufSelect.append("<option value='"+cRowSet.getString("seq")+"'>"+cRowSet.getString("group_name")+"</option>");
		}
	}
	sbufSelect.append("</select>");

	if(!sGroup.equals("0")){
		groupSeq = sGroup;
	}


	cRowSet = VocabularyDAO.getInstance().getVocabularyList(groupSeq);
	
	int num = 0;


      out.write(_jsp_string27, 0, _jsp_string27.length);
      
	if(sGroup.equals("0")){

      out.write(_jsp_string28, 0, _jsp_string28.length);
      out.print((sbufSelect));
      out.write(_jsp_string29, 0, _jsp_string29.length);
      
	}			

      out.write(_jsp_string30, 0, _jsp_string30.length);
      
		try{
			while(cRowSet.next()){
		
      out.write(_jsp_string31, 0, _jsp_string31.length);
      out.print((++num));
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((cRowSet.getString("seq")));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((cRowSet.getString("word")));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((cRowSet.getString("seq")));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((cRowSet.getString("group_name")));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((cRowSet.getString("seq")));
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((cRowSet.getString("seq")));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      
			}
		}
		catch(Exception e){
			log.debug(e);	
		}

		if(num == 0){
		
      out.write(_jsp_string37, 0, _jsp_string37.length);
      
		}
		
      out.write(_jsp_string38, 0, _jsp_string38.length);
      
	}
	catch(Exception e){
		log.fatal(e.getMessage(), e);
	}
	finally{
	}

      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "dnt7", "/WEB-INF/tlds/dnt7-com.tld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/vocabulary/vocabularyList.jsp"), 3277063621302502689L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/header.jsp"), 7226424049310249664L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/headerAdmin.jsp"), -8679113603297910256L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/needAdminLogin.jsp"), 1666710369671085L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/include/menu.jsp"), -752222935902637753L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/footerAdmin.jsp"), 2847583676638487941L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/footer.jsp"), -7402735715276527379L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string15;
  private final static char []_jsp_string6;
  private final static char []_jsp_string9;
  private final static char []_jsp_string22;
  private final static char []_jsp_string31;
  private final static char []_jsp_string21;
  private final static char []_jsp_string33;
  private final static char []_jsp_string29;
  private final static char []_jsp_string20;
  private final static char []_jsp_string27;
  private final static char []_jsp_string37;
  private final static char []_jsp_string30;
  private final static char []_jsp_string18;
  private final static char []_jsp_string19;
  private final static char []_jsp_string16;
  private final static char []_jsp_string34;
  private final static char []_jsp_string36;
  private final static char []_jsp_string4;
  private final static char []_jsp_string26;
  private final static char []_jsp_string2;
  private final static char []_jsp_string13;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string23;
  private final static char []_jsp_string28;
  private final static char []_jsp_string25;
  private final static char []_jsp_string3;
  private final static char []_jsp_string17;
  private final static char []_jsp_string38;
  private final static char []_jsp_string32;
  private final static char []_jsp_string11;
  private final static char []_jsp_string24;
  private final static char []_jsp_string14;
  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string12;
  private final static char []_jsp_string8;
  private final static char []_jsp_string0;
  private final static char []_jsp_string35;
  static {
    _jsp_string15 = "'\">\r\n								<a href=\"/admin/users/adminList.jsp\">\uad00\ub9ac\uc790 \uad00\ub9ac</a>\r\n							</dt>\r\n							".toCharArray();
    _jsp_string6 = " - \r\n								<a href=\"/admin/login/logout.jsp\" class=\"r_header\">Logout</a>\r\n								".toCharArray();
    _jsp_string9 = " pointer'\"\r\n								onclick=\"showMenu(1);\">\uad00\ub9ac\uc790 \uad00\ub9ac</dt>\r\n							<dt class=\"h_menu h_header_".toCharArray();
    _jsp_string22 = "\">\r\n							<dt class=\"top_title\">| \ud504\ub85c\uc81d\ud2b8 \uad00\ub9ac</dt>\r\n\r\n							<dt class=\"".toCharArray();
    _jsp_string31 = "\r\n		<tr>\r\n			<td class=\"ta_c\">".toCharArray();
    _jsp_string21 = "'\">\r\n								<a href=\"/admin/vocabulary/groupList.jsp\">\uacbd\ud5d8\uc5b4\ud718 \uadf8\ub8f9\uad00\ub9ac</a>\r\n							</dt>\r\n						</dl>\r\n\r\n						<!-- Menu 3 -->\r\n						<dl id=\"m3\" style=\"".toCharArray();
    _jsp_string33 = "\">".toCharArray();
    _jsp_string29 = "\r\n		&nbsp;&nbsp;&nbsp;&nbsp;\r\n		<input type=\"button\" value=\"Search\" style=\"width:50px;\" onclick='goSearch();' class=\"button white btn_in\" />\r\n	</div>\r\n".toCharArray();
    _jsp_string20 = "'\">\r\n								<a href=\"/admin/vocabulary/vocabularyList.jsp\">\uacbd\ud5d8\uc5b4\ud718 \uad00\ub9ac</a>\r\n							</dt>\r\n							<dt class=\"".toCharArray();
    _jsp_string27 = "\r\n<script type=\"text/javascript\">\r\nfunction goSearch(){\r\n	var frm = document.actFrm;\r\n\r\n	frm.submit();\r\n}\r\n\r\nfunction goDelete(seq)\r\n{\r\n	if(confirm(\"\uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?\")){\r\n		location.href = \"vocabularyProc.jsp?mode=Delete&seq=\"+seq;\r\n	}\r\n}\r\n</script>\r\n<div class=\"top_title\">\uc5b4\ud718 \uad00\ub9ac</div>\r\n<div id=\"search_form_inline\" style=\"clear:both;\">\r\n<form name=\"actFrm\" action=\"vocabularyList.jsp\">\r\n".toCharArray();
    _jsp_string37 = "\r\n		<tr>\r\n			<td colspan=\"4\" class=\"ta_c\">\ub4f1\ub85d\ub41c \uc5b4\ud718\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.</td>\r\n		</tr>\r\n		".toCharArray();
    _jsp_string30 = "\r\n</form>\r\n</div>\r\n\r\n<div id=\"roof_table\">\r\n	<table cellspacing=\"0\" cellpadding=\"0\" width=\"900px\">\r\n		<colgroup>\r\n			<col width=\"40px\" />\r\n			<col />\r\n			<col width=\"220px\"/>\r\n			<col width=\"140px\" />\r\n		</colgroup>\r\n		<thead>\r\n		<tr>\r\n			<th class=\"ta_c\">No.</th>\r\n			<th class=\"ta_c\">\uacbd\ud5d8\uc5b4\ud718</th>\r\n			<th class=\"ta_c\">\uadf8\ub8f9</th>\r\n			<th class=\"ta_c\">\uc218\uc815 / \uc0ad\uc81c</th>\r\n		</tr>\r\n		</thead>\r\n		<tbody>\r\n		".toCharArray();
    _jsp_string18 = "\r\n						</dl>\r\n\r\n\r\n						<!-- Menu 2 -->\r\n						<dl id=\"m2\" style=\"".toCharArray();
    _jsp_string19 = "\">\r\n							<dt class=\"top_title\">| \uacbd\ud5d8\uc5b4\ud718 \uad00\ub9ac</dt>\r\n							<dt class=\"".toCharArray();
    _jsp_string16 = "\r\n							<dt class=\"".toCharArray();
    _jsp_string34 = "</a></td>\r\n			<td class=\"ta_c\"><a href=\"vocabularyForm.jsp?seq=".toCharArray();
    _jsp_string36 = "')\">\uc0ad\uc81c</a></td>\r\n		</tr>\r\n		".toCharArray();
    _jsp_string4 = "\r\n\r\n<script type=\"text/javascript\">\r\nfunction showMenu(index){\r\n	var maxMenuIndex = 6;\r\n\r\n	for (var i=1 ; i <= maxMenuIndex ; i++)	{\r\n		if(i == index){\r\n			$(\"#m\" + i).show();\r\n		} else {\r\n			$(\"#m\" + i).hide();\r\n		}\r\n	}\r\n}\r\n\r\nfunction goMemberId(){\r\n	var frm = document.memberIdForm;\r\n	frm.submit();\r\n}\r\n</script>\r\n		<div id=\"header\"><!-- header \uc2dc\uc791 -->\r\n			<dl>\r\n				<dt class=\"h_logo\">\r\n					<a href=\"/admin/\" name=\"top\"><img src=\"/images/login_bgH.gif\" style=\"height:38px;\"/></a>\r\n				</dt>\r\n				<dd class=\"h_menu_top\">\r\n					<div>\r\n						<dl>\r\n							<dt style=\"float:right;text-align:right;\">\r\n								".toCharArray();
    _jsp_string26 = "'\">\r\n								<a href=\"/admin/stat/stat.jsp\">\ud1b5\uacc4 \uad00\ub9ac</a>\r\n							</dt>\r\n						</dl>\r\n						\r\n					</div>\r\n				</div><!-- left menu \ub05d -->\r\n				<div id=\"right_warp\"><!-- right \uc2dc\uc791 -->\r\n					<div id=\"right\">\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string13 = "\">\r\n							<dt class=\"top_title\">| \uad00\ub9ac\uc790 \uad00\ub9ac</dt>\r\n							<dt class=\"".toCharArray();
    _jsp_string5 = "\r\n								".toCharArray();
    _jsp_string1 = "\n\r\n".toCharArray();
    _jsp_string23 = "'\">\r\n								<a href=\"/admin/project/projectList.jsp\">\ud504\ub85c\uc81d\ud2b8 \uad00\ub9ac</a>\r\n							</dt>\r\n						</dl>\r\n						\r\n						\r\n						<!-- Menu 4 -->\r\n						<dl id=\"m4\" style=\"".toCharArray();
    _jsp_string28 = "\r\n	<div id=\"search_form_inline_in\">\r\n		Group : ".toCharArray();
    _jsp_string25 = "'\">\r\n								<a href=\"/admin/stat/projectMemberList.jsp\">\uc0ac\uc6a9\uc790 \uc124\uc815</a>\r\n							</dt>\r\n							<dt class=\"".toCharArray();
    _jsp_string3 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n<title> CESA : Admin </title>\r\n<!--[if IE 6]>\r\n	<script type=\"text/javascript\" src=\"/js/minmax.js\"></script>\r\n<![endif]-->\r\n<script type=\"text/javascript\" src=\"/js/jquery-1.4.2.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"/js/jquery-ui-1.8.6.custom.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"/js/jquery-block-ui.js\"></script>\r\n<script type=\"text/javascript\" src=\"/js/calendarpop.js\"></script>\r\n<script type=\"text/javascript\" src=\"/js/strFunction.js\"></script>\r\n<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js\"></script>\r\n<script src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js\"></script>\r\n\r\n<script type=\"text/javascript\" src=\"/js/jquery.form.js\"></script>\r\n\r\n<link href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/backoffice/css/default.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/backoffice/css/layout.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/backoffice/css/btn_ui.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/backoffice/css/login.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/backoffice/css/popup.css\" />\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/admin/extended.css\" />\r\n</head>\r\n\r\n<body>\r\n	<div id=\"all\" style=\"min-width:1200px;\"><!-- all \uc2dc\uc791 -->\r\n	<div id=\"mask\"></div>\r\n\r\n".toCharArray();
    _jsp_string17 = "'\">\r\n								<a href=\"/admin/users/groupList.jsp\">\uadf8\ub8f9 \uad00\ub9ac</a>\r\n							</dt>\r\n							".toCharArray();
    _jsp_string38 = "\r\n		</tbody>\r\n	</table>\r\n</div>\r\n\r\n<div class=\"btn_group_right_align\">\r\n	<input type=\"button\" onclick=\"document.location.href='vocabularyForm.jsp'\" value=\"Add\" class=\"button white\" style=\"width:33px;\"/>\r\n</div>\r\n\r\n\r\n\r\n					</div>\r\n				</div>\r\n			</div><!-- content \ub05d -->\r\n		</div><!-- all_content \ub05d -->\r\n\r\n		<div id=\"footer_all\">\r\n			<div style=\"width:100%;height:15px;background:#dadada\"></div>\r\n			<div style=\"width:100%;height:44px;background:url('/images/bg.jpg') repeat-x;\" ><img src=\"/backoffice/images/common/footer_bg.jpg\" alt=\"\ud558\ub2e8\uc774\ubbf8\uc9c0\" width=\"1200\" height=\"44\"/></div>\r\n\r\n			\r\n		</div>\r\n	\r\n	</div><!-- all \ub05d -->\r\n</body>\r\n</html>\r\n\r\n".toCharArray();
    _jsp_string32 = "</td>\r\n			<td class=\"ta_c\"><a href=\"vocabularyForm.jsp?seq=".toCharArray();
    _jsp_string11 = " pointer'\"\r\n								onclick=\"showMenu(3);\">\ud504\ub85c\uc81d\ud2b8 \uad00\ub9ac</dt>\r\n							<dt class=\"h_menu h_header_".toCharArray();
    _jsp_string24 = "\">\r\n							<dt class=\"top_title\">| \ud1b5\uacc4 \uad00\ub9ac</dt>\r\n							<dt class=\"".toCharArray();
    _jsp_string14 = "\"\r\n								onmouseover=\"this.className='depth2_sel pointer'\"\r\n								onmouseout=\"this.className='".toCharArray();
    _jsp_string7 = "\r\n							</dt>\r\n						</dl>\r\n					</div>\r\n				</dd>\r\n\r\n\r\n\r\n				<dd class=\"h_menu_list\" style=\"position:absolute;margin:30px 0 0 250px;\">\r\n\r\n					<div>\r\n						<dl>\r\n							<dt class=\"h_menu h_header_".toCharArray();
    _jsp_string10 = " pointer'\"\r\n								onclick=\"showMenu(2);\">\uacbd\ud5d8\uc5b4\ud718 \uad00\ub9ac</dt>\r\n							<dt class=\"h_menu h_header_".toCharArray();
    _jsp_string12 = " pointer'\"\r\n								onclick=\"showMenu(4);\">\ud1b5\uacc4 \uad00\ub9ac</dt>\r\n						</dl>\r\n					</div>\r\n				</dd>\r\n			</dl>\r\n\r\n		</div> <!-- header \ub05d -->\r\n		\r\n		<div id=\"header_gradation\"></div>\r\n		\r\n		<div id=\"all_container\"><!-- all_container \uc2dc\uc791 -->\r\n			<div id=\"content\"> <!-- content \uc2dc\uc791 -->\r\n			\r\n				<div  id=\"left_warp\"><!-- left menu \uc2dc\uc791 -->\r\n					<div id=\"left\" >\r\n						<!-- Menu 1 -->\r\n						<dl id=\"m1\" style=\"".toCharArray();
    _jsp_string8 = " pointer\"\r\n								onmouseover=\"this.className='h_menu h_header_on pointer'\"\r\n								onmouseout=\"this.className='h_menu h_header_".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
    _jsp_string35 = "\">\uc218\uc815</a> / <a href=\"javascript:goDelete('".toCharArray();
  }
}
